services:
  - type: web
    name: stock-trading-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: FINNHUB_API_TOKEN
        sync: false
      - key: POLYGON_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
